version: "3.8"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./scripts:/home/jovyan/work
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          memory: 11g
        reservations:
          memory: 8g

  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./database/data:/database/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./database/data/dell_data.json:/database/data/dell_data.json
      - ./database/data/ibm_data.json:/database/data/ibm_data.json
      - ./database/data/intel_data.json:/database/data/intel_data.json
      - ./database/data/microsoft_data.json:/database/data/microsoft_data.json
      - ./database/data/sony_data.json:/database/data/sony_data.json
      - ./database/data/nvidia_data.json:/database/data/nvidia_data.json
      - ./database/data/youtube_data_us.json:/database/data/youtube_data_us.json
      - ./database/data/youtube_data_br.json:/database/data/youtube_data_br.json
      - ./database/data/youtube_data_ca.json:/database/data/youtube_data_ca.json
      - ./database/data/youtube_data_de.json:/database/data/youtube_data_de.json
      - ./database/data/youtube_data_fr.json:/database/data/youtube_data_fr.json
      - ./database/data/youtube_data_gb.json:/database/data/youtube_data_gb.json
      - ./database/data/youtube_data_in.json:/database/data/youtube_data_in.json
      - ./database/data/youtube_data_jp.json:/database/data/youtube_data_jp.json
      - ./database/data/youtube_data_kr.json:/database/data/youtube_data_kr.json
      - ./database/data/youtube_data_mx.json:/database/data/youtube_data_mx.json
      - ./database/data/youtube_data_ru.json:/database/data/youtube_data_ru.json


